config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  get 'call', to: 'call#user', as: 'call_user'
  post 'call', to: 'call#create'

  resources :rooms do
    resources :messages
    collection do
      post :search
    end
  end
  # leave_room_path(room)
  get 'rooms/leave/:id', to: 'rooms#leave', as: 'leave_room'
  # join_room_path(room)
  get 'rooms/join/:id', to: 'rooms#join', as: 'join_room'

  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<div class="row" style="margin:0px; padding: 0px">
  <div class="col-8" style="padding: 0px">
    <div class="card p-5">
      <h1>Harmony</h1>
      <p>There are <strong><%= pluralize(@online_users, "User") %></strong> Online.</p>
      <p>Ruby projekt</p>
      <% if current_user %>
        <div class="btn-group">
          <%= link_to "Start Chatting", rooms_path, class:'btn btn-primary' %>
          <%= link_to "Edit Account", edit_user_registration_path, class:'btn btn-secondary' %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class:'btn btn-danger' %>
        </div>
      <% else %>
        <div class="btn-group">
          <%= link_to "Login", new_user_session_path, class:'btn btn-primary' %>
          <%= link_to "Sign Up", new_user_registration_path, class:'btn btn-secondary' %>
        </div><%=  %>
      <% end %>
    </div>
  </div>

  <%= turbo_stream_from "public_messages" %>
  <div class="col-4" id="public_messages" style="overflow: hidden; height: calc(100vh-56px); padding: 0px;">
    <% @messages.each do |message| %>
      <%= render "messages/message_preview", message: message %>
    <% end %>
  </div>
</div>